### ISSUE TITLE
error Missing script: "build"

### ISSUE THREAD

**Issue by the-centry** [SymbiFlow/symbiflow-bitstream-viewer#13]
0 verbose cli [
0 verbose cli   '/root/Desktop/project/f4pga-bitstream-viewer/nenv/bin/node',
0 verbose cli   '/root/Desktop/project/f4pga-bitstream-viewer/nenv/bin/npm',
0 verbose cli   'run',
0 verbose cli   'build',
0 verbose cli   'App.vue'
0 verbose cli ]
1 info using npm@8.5.1
2 info using node@v17.6.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/root/Desktop/project/f4pga-bitstream-viewer/nenv/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/root/Desktop/project/f4pga-bitstream-viewer/.npmrc Completed in 0ms
10 timing config:load:project Completed in 9ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/root/Desktop/project/f4pga-bitstream-viewer/nenv/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 16ms
19 timing npm:load:configload Completed in 16ms
20 timing npm:load:setTitle Completed in 0ms
21 timing config:load:flatten Completed in 2ms
22 timing npm:load:display Completed in 3ms
23 verbose logfile /root/.npm/_logs/2022-02-28T07_48_22_153Z-debug-0.log
24 timing npm:load:logFile Completed in 4ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 23ms
28 silly logfile start cleaning logs, removing 2 files
29 timing command:run Completed in 6ms
30 verbose stack Error: Missing script: "build"
30 verbose stack
30 verbose stack To see a list of scripts, run:
30 verbose stack   npm run
30 verbose stack     at RunScript.run (/root/Desktop/project/f4pga-bitstream-viewer/nenv/lib/node_modules/npm/lib/commands/run-script.js:95:13)
30 verbose stack     at async module.exports (/root/Desktop/project/f4pga-bitstream-viewer/nenv/lib/node_modules/npm/lib/cli.js:66:5)
31 verbose cwd /root/Desktop/project/f4pga-bitstream-viewer
32 verbose Linux 5.4.0-100-generic
33 verbose argv "/root/Desktop/project/f4pga-bitstream-viewer/nenv/bin/node" "/root/Desktop/project/f4pga-bitstream-viewer/nenv/bin/npm" "run" "build" "App.vue"
34 verbose node v17.6.0
35 verbose npm  v8.5.1
36 error Missing script: "build"
36 error
36 error To see a list of scripts, run:
36 error   npm run
37 verbose exit 1
38 timing npm Completed in 140ms
39 verbose code 1
40 error A complete log of this run can be found in:
40 error     /root/.npm/_logs/2022-02-28T07_48_22_153Z-debug-0.log

**Comment by the-centry** [comment]
> sovled [https://github.com/the-centry/f4pga-bitstream-viewer](https://github.com/the-centry/f4pga-bitstream-viewer)
